version: '3.8'

services:
  # --- 1. СУБД: ОБЩАЯ БАЗА ДАННЫХ ДЛЯ ВСЕХ СЕРВИСОВ ---
  db:
    image: mariadb:10.11
    container_name: migration_mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=F@il2511 # Твой основной пароль СУБД из ТЗ
    networks:
      - migration_net

  # --- 2. ВЕБ-ПРОКСИ И SSL-МЕНЕДЖЕР (Nginx Proxy Manager) ---
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: migration_proxy
    restart: always
    ports:
      - '80:80'       # HTTP трафик для prodick.ru
      - '443:443'     # HTTPS защищенный трафик (сайт + веб-лазейка)
    volumes:
      - ./data/nginx/data:/data
      - ./data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - migration_net

  # --- 3. ТЕЛЕФОНИЯ: FREEPBX ---
  freepbx:
    image: tiredofit/freepbx:latest
    container_name: migration_freepbx
    restart: always
    privileged: true          # <--- ТЕПЕРЬ ОН СТРОГО НА СВОЕМ МЕСТЕ (4 пробела)
    ports:
      - '5060:5060/udp'       # SIP сигнализация
      - '5160:5160/udp'       # Альтернативный SIP
      - '10000-10050:10000-10050/udp' # RTP порты для голоса (минимальный диапазон)
    volumes:
      - ./data/freepbx/data:/data
      - ./data/freepbx/logs:/var/log
    environment:
      - DB_HOST=db
      - DB_NAME=asterisk
      - DB_USER=root
      - DB_PASS=F@il2511
    networks:
      - migration_net

  # --- 7. СЛУЖЕБНАЯ ЛАЗЕЙКА: СКРЫТЫЙ ВЕБ-ТЕРМИНАЛ (SSH через браузер) ---
  wetty:
    image: wettyoss/wetty:latest
    container_name: migration_terminal
    restart: always
    ports:
      - '3000:3000' # Спрячем за прокси Nginx Proxy Manager
    environment:
      - SSHHOST=10.10.0.10 # Локальный IP твоей новой Ubuntu
      - SSHPORT=4422       # Измененный скрытый порт SSH хоста Ubuntu (вместо дефолтного 22)
      - BASE=/terminal/   # Секретный URL (доступ по адресу: prodick.ru/terminal/)
    networks:
      - migration_net

networks:
  migration_net:
    driver: bridge
